gae: ZO changed their time string format
ValueError: time data '22 03 2020 1340 Uhr' does not match format '%d %m %Y %H:%M Uhr'

Not sure if that's temporary or not
but it was changed to

22. März 2020, 13.55 Uhr

(colon replaced with .)